"""
Ontario Cities Reference List (Generated from NAR 2024)
This module provides a comprehensive list of valid Ontario cities,
extracted from Statistics Canada National Address Register 2024.
"""

# Valid Ontario cities and municipalities
# Source: NAR 2024 - 1,153 cities with ≥5 addresses
# Generated: 2025-10-03
VALID_ONTARIO_CITIES = {
    "ACTON",
    "ADDISON",
    "AHMIC HARBOUR",
    "AILSA CRAIG",
    "AJAX",
    "AKWESASNE",
    "ALBAN",
    "ALBERTON",
    "ALEXANDRIA",
    "ALFRED",
    "ALGOMA MILLS",
    "ALGONQUIN HIGHLANDS",
    "ALLANBURG",
    "ALLENFORD",
    "ALLISTON",
    "ALMA",
    "ALMONTE",
    "ALTON",
    "ALVINSTON",
    "AMARANTH",
    "AMELIASBURG",
    "AMHERSTBURG",
    "AMHERSTVIEW",
    "ANCASTER",
    "ANGUS",
    "ANNAN",
    "APPIN",
    "APPLE HILL",
    "APSLEY",
    "ARDEN",
    "ARDOCH",
    "ARISS",
    "ARKELL",
    "ARKONA",
    "ARMSTRONG STATION",
    "ARNPRIOR",
    "ARNSTEIN",
    "AROLAND",
    "ARTHUR",
    "ARVA",
    "ASHBURN",
    "ASHTON",
    "ASPHODEL-NORWOOD",
    "ASTORVILLE",
    "ATHENS",
    "ATIKOKAN",
    "ATTAWAPISKAT",
    "ATWOOD",
    "AUBURN",
    "AUGUSTA",
    "AURORA",
    "AVONMORE",
    "AWERES TWP",
    "AYLMER",
    "AYR",
    "AYTON",
    "AZILDA",
    "BADEN",
    "BADJEROS",
    "BAILIEBORO",
    "BAINSVILLE",
    "BALA",
    "BALDERSON",
    "BALDWIN",
    "BALLINAFAD",
    "BALMERTOWN",
    "BALTIMORE",
    "BANCROFT",
    "BARRIE",
    "BARRYS BAY",
    "BARWICK",
    "BATAWA",
    "BATCHEWANA FIRST NATION",
    "BATH",
    "BATTERSEA",
    "BAYFIELD",
    "BAYSVILLE",
    "BEACHBURG",
    "BEACHVILLE",
    "BEAMSVILLE",
    "BEARDMORE",
    "BEAUMARIS",
    "BEAVERTON",
    "BEETON",
    "BELFOUNTAIN",
    "BELGRAVE",
    "BELLE EWART",
    "BELLE RIVER",
    "BELLE VALLEE",
    "BELLE VALLÉE",
    "BELLEVILLE",
    "BELMONT",
    "BELWOOD",
    "BERKELEY",
    "BERWICK",
    "BETHANY",
    "BEWDLEY",
    "BINBROOK",
    "BIRCH ISLAND",
    "BLACKSTOCK",
    "BLENHEIM",
    "BLEZARD VALLEY",
    "BLIND RIVER",
    "BLOOMFIELD",
    "BLOOMINGDALE",
    "BLUE MOUNTAINS",
    "BLUEVALE",
    "BLYTH",
    "BOBCAYGEON",
    "BOGNOR",
    "BOLSOVER",
    "BOLTON",
    "BOND HEAD",
    "BONFIELD",
    "BORDEN",
    "BORNHOLM",
    "BOTHWELL",
    "BOURGET",
    "BOWMANVILLE",
    "BRACEBRIDGE",
    "BRADFORD",
    "BRAESIDE",
    "BRAMPTON",
    "BRANCHTON",
    "BRANTFORD",
    "BRECHIN",
    "BRESLAU",
    "BRIDGENORTH",
    "BRIGDEN",
    "BRIGHT",
    "BRIGHT'S GROVE",
    "BRIGHTON",
    "BRINSTON",
    "BRITT",
    "BROCKTON",
    "BROCKVILLE",
    "BRODHAGEN",
    "BROWNSVILLE",
    "BRUCE MINES",
    "BRUCEFIELD",
    "BRUNNER",
    "BRUSSELS",
    "BUCKHORN",
    "BURFORD",
    "BURGESSVILLE",
    "BURKS FALLS",
    "BURLINGTON",
    "BURNSTOWN",
    "BURNT RIVER",
    "BURRITTS RAPIDS",
    "BYNG INLET",
    "CACHE BAY",
    "CAESAREA",
    "CAISTOR CENTRE",
    "CALABOGIE",
    "CALEDON",
    "CALEDON EAST",
    "CALEDON VILLAGE",
    "CALEDONIA",
    "CALLANDER",
    "CAMBRAY",
    "CAMBRIDGE",
    "CAMDEN EAST",
    "CAMERON",
    "CAMLACHIE",
    "CAMPBELLCROFT",
    "CAMPBELLFORD",
    "CAMPBELLVILLE",
    "CAMPDEN",
    "CANFIELD",
    "CANNIFTON",
    "CANNINGTON",
    "CAPREOL",
    "CARAMAT",
    "CARDIFF",
    "CARDINAL",
    "CARGILL",
    "CARLETON PLACE",
    "CARLISLE",
    "CARLSBAD SPRINGS",
    "CARP",
    "CARRYING PLACE",
    "CARTIER",
    "CASSELMAN",
    "CASTLETON",
    "CATHCART",
    "CAVAN",
    "CAVAN MONAGHAN",
    "CAYUGA",
    "CEDAR SPRINGS",
    "CEDAR VALLEY",
    "CENTRALIA",
    "CENTREVILLE",
    "CHALK RIVER",
    "CHAPLEAU",
    "CHAPUT HUGHES",
    "CHARING CROSS",
    "CHARLTON",
    "CHATHAM",
    "CHATSWORTH",
    "CHELMSFORD",
    "CHELTENHAM",
    "CHEPSTOW",
    "CHERRY VALLEY",
    "CHESLEY",
    "CHESTERVILLE",
    "CHRISTIAN ISLAND",
    "CHURCHILL",
    "CHUTE A BLONDEAU",
    "CLARENCE CREEK",
    "CLARENDON STATION",
    "CLARKSBURG",
    "CLAYTON",
    "CLEAR CREEK",
    "CLIFFORD",
    "CLINTON",
    "CLOYNE",
    "COATSWORTH STATION",
    "COBALT",
    "COBDEN",
    "COBOCONK",
    "COBOURG",
    "COCHENOUR",
    "COCHRANE",
    "CODRINGTON",
    "COE HILL",
    "COLBORNE",
    "COLDWATER",
    "COLLINGWOOD",
    "COMBER",
    "COMBERMERE",
    "CONCORD",
    "CONESTOGO",
    "CONISTON",
    "CONN",
    "CONNAUGHT",
    "CONSECON",
    "COOKSTOWN",
    "COPETOWN",
    "COPPER CLIFF",
    "CORBEIL",
    "CORBYVILLE",
    "CORMAC",
    "CORNWALL",
    "CORUNNA",
    "COTTAM",
    "COUNTY OF BRANT",
    "COURTICE",
    "COURTLAND",
    "COURTRIGHT",
    "CREDITON",
    "CREEMORE",
    "CROTON",
    "CRYSLER",
    "CRYSTAL BEACH",
    "CRYSTAL FALLS",
    "CUMBERLAND",
    "CUMBERLAND BEACH",
    "CURRAN",
    "CUTLER",
    "DACRE",
    "DALKEITH",
    "DALLES",
    "DASHWOOD",
    "DEEP RIVER",
    "DELAWARE",
    "DELHI",
    "DELTA",
    "DEMORESTVILLE",
    "DENBIGH",
    "DENFIELD",
    "DESBARATS",
    "DESBORO",
    "DESERONTO",
    "DEUX RIVIÈRES",
    "DEVLIN",
    "DOBBINTON",
    "DOBIE",
    "DOKIS FIRST NATION",
    "DORCHESTER",
    "DORION",
    "DORSET",
    "DOUGLAS",
    "DOURO-DUMMER",
    "DOVER CENTRE",
    "DOWLING",
    "DRAYTON",
    "DRESDEN",
    "DRUMBO",
    "DRYDEN",
    "DUART",
    "DUBLIN",
    "DUBREUILVILLE",
    "DUNCHURCH",
    "DUNDALK",
    "DUNDAS",
    "DUNGANNON",
    "DUNNVILLE",
    "DUNROBIN",
    "DUNSFORD",
    "DUNTROON",
    "DUNVEGAN",
    "DURHAM",
    "DUTTON",
    "DWIGHT",
    "EAGLE LAKE",
    "EAGLE RIVER",
    "EAR FALLS",
    "EARLTON",
    "EAST GARAFRAXA",
    "EAST GWILLIMBURY",
    "EAST YORK",
    "ECHO BAY",
    "EDEN",
    "EDEN MILLS",
    "EDWARDS",
    "EGANVILLE",
    "EGBERT",
    "EGMONDVILLE",
    "ELDORADO",
    "ELGIN",
    "ELGINBURG",
    "ELIZABETHTOWN",
    "ELK LAKE",
    "ELLIOT LAKE",
    "ELMIRA",
    "ELMVALE",
    "ELMWOOD",
    "ELORA",
    "EMBRO",
    "EMBRUN",
    "EMERYVILLE",
    "EMO",
    "EMSDALE",
    "ENGLEHART",
    "ENNISMORE",
    "ENTERPRISE",
    "ERIEAU",
    "ERIN",
    "ERINSVILLE",
    "ESPANOLA",
    "ESSEX",
    "ETHEL",
    "ETOBICOKE",
    "EVANSVILLE",
    "EVERETT",
    "EXETER",
    "FALCONBRIDGE",
    "FAUQUIER",
    "FENELON FALLS",
    "FENWICK",
    "FERGUS",
    "FEVERSHAM",
    "FIELD",
    "FINCH",
    "FINGAL",
    "FISHERVILLE",
    "FITZROY HARBOUR",
    "FLESHERTON",
    "FLINTON",
    "FLORADALE",
    "FLORENCE",
    "FONTHILL",
    "FORDWICH",
    "FOREST",
    "FORESTERS FALLS",
    "FORMOSA",
    "FORT ERIE",
    "FORT FRANCES",
    "FORT WILLIAM FIRST NATION",
    "FOURNIER",
    "FOWLER",
    "FOXBORO",
    "FOYMOUNT",
    "FRANKFORD",
    "FRANKVILLE",
    "FRASERVILLE",
    "FREELTON",
    "FULLARTON",
    "GADS HILL",
    "GANANOQUE",
    "GARDEN RIVER",
    "GARDEN VILLAGE",
    "GARSON",
    "GEORGETOWN",
    "GEORGIAN BLUFFS",
    "GERALDTON",
    "GILFORD",
    "GILMOUR",
    "GLEN HURON",
    "GLEN MORRIS",
    "GLEN ROBERTSON",
    "GLEN WILLIAMS",
    "GLENBURNIE",
    "GLENCAIRN",
    "GLENCOE",
    "GLOUCESTER",
    "GODERICH",
    "GODFREY",
    "GOGAMA",
    "GOLDEN LAKE",
    "GOLDEN VALLEY",
    "GOODERHAM",
    "GOODWOOD",
    "GORE BAY",
    "GORES LANDING",
    "GORHAM",
    "GORMLEY",
    "GORRIE",
    "GOULAIS RIVER",
    "GOWANSTOWN",
    "GRAFTON",
    "GRAND BEND",
    "GRAND VALLEY",
    "GRANDE POINTE",
    "GRANTON",
    "GRASSIE",
    "GRAVENHURST",
    "GREATER MADAWASKA",
    "GREELY",
    "GREEN VALLEY",
    "GREENBANK",
    "GRIFFITH",
    "GRIMSBY",
    "GUELPH",
    "HAGAR",
    "HAGERSVILLE",
    "HAILEYBURY",
    "HALEY STATION",
    "HALIBURTON",
    "HAMILTON",
    "HAMILTON TOWNSHIP",
    "HAMMOND",
    "HAMPTON",
    "HANMER",
    "HANNON",
    "HANOVER",
    "HARCOURT",
    "HARLEY",
    "HARRIETSVILLE",
    "HARRISTON",
    "HARROW",
    "HARROWSMITH",
    "HARTINGTON",
    "HARTY",
    "HARWOOD",
    "HASTINGS",
    "HAVELOCK",
    "HAWK JUNCTION",
    "HAWKESBURY",
    "HAWKESVILLE",
    "HAY",
    "HAYDON",
    "HBMTWP",
    "HEARST",
    "HEATHCOTE",
    "HEIDELBERG",
    "HENSALL",
    "HEPWORTH",
    "HERON BAY",
    "HIAWATHA",
    "HIGHGATE",
    "HIGHLAND GROVE",
    "HILLIARDTON",
    "HILLIER",
    "HILLSBURGH",
    "HILLSDALE",
    "HILTON BEACH",
    "HOLLAND CENTRE",
    "HOLLAND LANDING",
    "HOLSTEIN",
    "HOLTYRE",
    "HOLYROOD",
    "HONEY HARBOUR",
    "HORNBY",
    "HORNELL HEIGHTS",
    "HORNEPAYNE",
    "HORTON",
    "HUDSON",
    "HUNTSVILLE",
    "IGNACE",
    "ILDERTON",
    "INDIAN RIVER",
    "INGERSOLL",
    "INGLESIDE",
    "INGLEWOOD",
    "INKERMAN",
    "INNERKIP",
    "INNISFIL",
    "INVERARY",
    "INWOOD",
    "IONA STATION",
    "IRON BRIDGE",
    "IROQUOIS",
    "IROQUOIS FALLS",
    "IROQUOIS FALLS A",
    "JACKSONS POINT",
    "JACQUES",
    "JANETVILLE",
    "JARVIS",
    "JASPER",
    "JERSEYVILLE",
    "JOGUES",
    "JOHNSTOWN",
    "JORDAN STATION",
    "JOYCEVILLE",
    "KAGAWONG",
    "KAKABEKA FALLS",
    "KALADAR",
    "KAMINISTIQUIA",
    "KANATA",
    "KAPUSKASING",
    "KARS",
    "KATRINE",
    "KEARNEY",
    "KEARNS",
    "KEENE",
    "KEEWATIN",
    "KEMBLE",
    "KEMPTVILLE",
    "KENDAL",
    "KENILWORTH",
    "KENMORE",
    "KENORA",
    "KENT BRIDGE",
    "KERWOOD",
    "KESWICK",
    "KETTLE AND STONY POINT FN",
    "KILLALOE",
    "KILLARNEY",
    "KILWORTHY",
    "KIMBERLEY",
    "KINBURN",
    "KINCARDINE",
    "KING",
    "KING CITY",
    "KING KIRKLAND",
    "KINGSTON",
    "KINGSVILLE",
    "KINMOUNT",
    "KINTORE",
    "KIPPEN",
    "KIRKFIELD",
    "KIRKLAND LAKE",
    "KIRKTON",
    "KITCHENER",
    "KLEINBURG",
    "KOMOKA",
    "L'AMABLE",
    "L'ORIGNAL",
    "LA SALETTE",
    "LAKE ST PETER",
    "LAKEFIELD",
    "LAKEHURST",
    "LAKESIDE",
    "LAMBTON SHORES",
    "LANARK",
    "LANCASTER",
    "LANGTON",
    "LANSDOWNE",
    "LARDER LAKE",
    "LASALLE",
    "LATCHFORD",
    "LAVIGNE",
    "LEAMINGTON",
    "LEASKDALE",
    "LEFAIVRE",
    "LEFROY",
    "LEVACK",
    "LIMEHOUSE",
    "LIMOGES",
    "LINCOLN",
    "LINDSAY",
    "LINWOOD",
    "LIONS HEAD",
    "LISLE",
    "LISTOWEL",
    "LITTLE BRITAIN",
    "LITTLE CURRENT",
    "LIVELY",
    "LOCUST HILL",
    "LOMBARDY",
    "LONDESBOROUGH",
    "LONDON",
    "LONG SAULT",
    "LONGFORD MILLS",
    "LONGLAC",
    "LORETTO",
    "LOWBANKS",
    "LUCAN",
    "LUCKNOW",
    "LUNENBURG",
    "LYN",
    "LYNDEN",
    "LYNDHURST",
    "M'CHIGEENG",
    "MABERLY",
    "MACDIARMID",
    "MACKEY",
    "MACTIER",
    "MADAWASKA",
    "MADOC",
    "MADSEN",
    "MAGNETAWAN",
    "MAIDSTONE",
    "MAITLAND",
    "MALLORYTOWN",
    "MANILLA",
    "MANITOUWADGE",
    "MANITOWANING",
    "MANOTICK",
    "MANSFIELD",
    "MAPLE",
    "MAPLE LEAF",
    "MAR",
    "MARATHON",
    "MARKDALE",
    "MARKHAM",
    "MARKSTAY",
    "MARLBANK",
    "MARMORA",
    "MARTEN RIVER",
    "MARTINTOWN",
    "MARYHILL",
    "MARYSVILLE",
    "MASSEY",
    "MATACHEWAN",
    "MATHESON",
    "MATTAWA",
    "MATTICE",
    "MAXVILLE",
    "MAXWELL",
    "MAYNOOTH",
    "MCARTHURS MILLS",
    "MCDONALDS CORNERS",
    "MCDOUGALL",
    "MCGREGOR",
    "MCKELLAR",
    "MCKENZIE ISLAND",
    "MCKERROW",
    "MCNAB/BRAESIDE",
    "MEAFORD",
    "MELANCTHON",
    "MELBOURNE",
    "MELDRUM BAY",
    "MERLIN",
    "MERRICKVILLE",
    "METCALFE",
    "MIDHURST",
    "MIDLAND",
    "MIGISI SAHGAIGAN",
    "MILDMAY",
    "MILFORD",
    "MILFORD BAY",
    "MILLBANK",
    "MILLBROOK",
    "MILLER LAKE",
    "MILLGROVE",
    "MILTON",
    "MILVERTON",
    "MINDEMOYA",
    "MINDEN",
    "MINESING",
    "MINETT",
    "MINNITAKI",
    "MISSISSAUGA",
    "MITCHELL",
    "MOFFAT",
    "MONETVILLE",
    "MONKLAND",
    "MONKTON",
    "MONO",
    "MONTEITH",
    "MOONBEAM",
    "MOOREFIELD",
    "MOORETOWN",
    "MOOSE CREEK",
    "MOOSE FACTORY",
    "MOOSONEE",
    "MOREWOOD",
    "MORPETH",
    "MORRISBURG",
    "MORRISTON",
    "MOSSLEY",
    "MOUNT ALBERT",
    "MOUNT BRYDGES",
    "MOUNT ELGIN",
    "MOUNT FOREST",
    "MOUNT HOPE",
    "MOUNT PLEASANT",
    "MOUNTAIN",
    "MOUNTAIN GROVE",
    "MUIRKIRK",
    "MULMUR",
    "MUNCEY",
    "MUNSTER",
    "MURILLO",
    "NAIRN CENTRE",
    "NAKINA",
    "NANTICOKE",
    "NAPANEE",
    "NAUGHTON",
    "NAVAN",
    "NEEBING",
    "NEPEAN",
    "NESTLETON STATION",
    "NESTOR FALLS",
    "NEUSTADT",
    "NEW DUNDEE",
    "NEW HAMBURG",
    "NEW LISKEARD",
    "NEW LOWELL",
    "NEW TECUMSETH",
    "NEWBORO",
    "NEWBURGH",
    "NEWBURY",
    "NEWCASTLE",
    "NEWINGTON",
    "NEWMARKET",
    "NEWTON",
    "NEWTONVILLE",
    "NEYAASHIINIGMIING",
    "NIAGARA FALLS",
    "NIAGARA ON THE LAKE",
    "NIPIGON",
    "NIPISSING",
    "NOBEL",
    "NOBLETON",
    "NOELVILLE",
    "NOLALU",
    "NORLAND",
    "NORTH AUGUSTA",
    "NORTH BAY",
    "NORTH BUXTON",
    "NORTH COBALT",
    "NORTH GOWER",
    "NORTH KAWARTHA",
    "NORTH LANCASTER",
    "NORTH YORK",
    "NORTHBROOK",
    "NORTHERN BRUCE PENINSULA",
    "NORVAL",
    "NORWICH",
    "NORWOOD",
    "NOTTAWA",
    "NOVAR",
    "OAKLAND",
    "OAKVILLE",
    "OAKWOOD",
    "ODESSA",
    "OHSWEKEN",
    "OIL CITY",
    "OIL SPRINGS",
    "OLDCASTLE",
    "OMEMEE",
    "OMPAH",
    "ONAPING",
    "OPASATIKA",
    "ORANGEVILLE",
    "ORILLIA",
    "ORLÉANS",
    "ORO-MEDONTE",
    "ORONO",
    "ORTON",
    "OSGOODE",
    "OSHAWA",
    "OTONABEE",
    "OTTAWA",
    "OTTERVILLE",
    "OWEN SOUND",
    "OXDRIFT",
    "OXFORD MILLS",
    "OXFORD STATION",
    "PAIN COURT",
    "PAISLEY",
    "PAKENHAM",
    "PALGRAVE",
    "PALMER RAPIDS",
    "PALMERSTON",
    "PARHAM",
    "PARIS",
    "PARKHILL",
    "PARRY SOUND",
    "PASS LAKE",
    "PAYS PLAT",
    "PEFFERLAW",
    "PELEE ISLAND",
    "PEMBROKE",
    "PENETANGUISHENE",
    "PERTH",
    "PERTH ROAD",
    "PETAWAWA",
    "PETERBOROUGH",
    "PETERSBURG",
    "PETROLIA",
    "PHELPSTON",
    "PICKEREL",
    "PICKERING",
    "PICKLE LAKE",
    "PICTON",
    "PIKWÀKANAGÀN",
    "PINEWOOD",
    "PLAINFIELD",
    "PLANTAGENET",
    "PLATTSVILLE",
    "PLEVNA",
    "POINT EDWARD",
    "POINTE AUX ROCHES",
    "POINTE-AU-BARIL-STATION",
    "POINTE-AUX-ROCHES",
    "PONTYPOOL",
    "PORCUPINE",
    "PORQUIS JUNCTION",
    "PORT ALMA",
    "PORT BURWELL",
    "PORT CARLING",
    "PORT COLBORNE",
    "PORT DOVER",
    "PORT ELGIN",
    "PORT FRANKS",
    "PORT HOPE",
    "PORT LAMBTON",
    "PORT LORING",
    "PORT MCNICOLL",
    "PORT PERRY",
    "PORT ROBINSON",
    "PORT ROWAN",
    "PORT SEVERN",
    "PORT STANLEY",
    "PORT SYDNEY",
    "PORTLAND",
    "POWASSAN",
    "PRESCOTT",
    "PRICEVILLE",
    "PRINCE ALBERT",
    "PRINCE TWP",
    "PRINCETON",
    "PROTON STATION",
    "PROVIDENCE BAY",
    "PUSLINCH",
    "PUTNAM",
    "QUADEVILLE",
    "QUEENSTON",
    "QUEENSVILLE",
    "QUINTE WEST",
    "RAINY RIVER",
    "RAMA",
    "RAMARA",
    "RAMORE",
    "RAMSAYVILLE",
    "RAVENNA",
    "REABORO",
    "RED LAKE",
    "RED ROCK",
    "REDBRIDGE",
    "RENFREW",
    "RICHARDS LANDING",
    "RICHMOND",
    "RICHMOND HILL",
    "RIDGETOWN",
    "RIDGEVILLE",
    "RIDGEWAY",
    "RIPLEY",
    "RIVER DRIVE PARK",
    "RIVER VALLEY",
    "ROBLIN",
    "ROCKCLIFFE",
    "ROCKLAND",
    "ROCKPORT",
    "ROCKTON",
    "ROCKWOOD",
    "RODNEY",
    "ROLPHTON",
    "ROSEMONT",
    "ROSENEATH",
    "ROSLIN",
    "ROSSEAU",
    "ROSSLYN",
    "ROSTOCK",
    "ROUND LAKE CENTRE",
    "RUSCOM STATION",
    "RUSSELL",
    "RUTHERGLEN",
    "RUTHVEN",
    "SAINT-PASCAL-BAYLON",
    "SALFORD",
    "SANDFORD",
    "SARNIA",
    "SARSFIELD",
    "SAUBLE BEACH",
    "SAULT STE. MARIE",
    "SCARBOROUGH",
    "SCHOMBERG",
    "SCHREIBER",
    "SCHUMACHER",
    "SCOTLAND",
    "SEAFORTH",
    "SEAGRAVE",
    "SEARCHMONT",
    "SEBRIGHT",
    "SEBRINGVILLE",
    "SEELEYS BAY",
    "SEGUIN",
    "SELBY",
    "SELKIRK",
    "SELWYN",
    "SERPENT RIVER",
    "SESEKINIKA",
    "SEVERN",
    "SEVERN BRIDGE",
    "SHAKESPEARE",
    "SHALLOW LAKE",
    "SHANNONVILLE",
    "SHARBOT LAKE",
    "SHARON",
    "SHEDDEN",
    "SHEFFIELD",
    "SHEGUIANDAH",
    "SHELBURNE",
    "SHERKSTON",
    "SHESHEGWANING",
    "SHUNIAH",
    "SILVER WATER",
    "SIMCOE",
    "SINGHAMPTON",
    "SIOUX LOOKOUT",
    "SIOUX NARROWS",
    "SKEAD",
    "SLATE RIVER",
    "SLEEMAN",
    "SMITHS FALLS",
    "SMITHVILLE",
    "SMOOTH ROCK FALLS",
    "SNOW ROAD STATION",
    "SOMBRA",
    "SOUTH BRUCE PENINSULA",
    "SOUTH GILLIES",
    "SOUTH GLENGARRY",
    "SOUTH LANCASTER",
    "SOUTH MOUNTAIN",
    "SOUTH PORCUPINE",
    "SOUTH RIVER",
    "SOUTH STORMONT",
    "SOUTH WOODSLEE",
    "SOUTHAMPTON",
    "SOUTHWOLD",
    "SPANISH",
    "SPARTA",
    "SPENCERVILLE",
    "SPRAGGE",
    "SPRING BAY",
    "SPRINGBROOK",
    "SPRINGFIELD",
    "SPRINGFORD",
    "SPRINGWATER",
    "SPRUCEDALE",
    "ST AGATHA",
    "ST ALBERT",
    "ST ANDREWS WEST",
    "ST ANNS",
    "ST BERNARDIN",
    "ST CATHARINES",
    "ST CHARLES",
    "ST CLEMENTS",
    "ST DAVIDS",
    "ST EUGENE",
    "ST GEORGE",
    "ST GEORGE BRANT",
    "ST ISIDORE",
    "ST JACOBS",
    "ST JOACHIM",
    "ST MARYS",
    "ST THOMAS",
    "ST WILLIAMS",
    "ST. PAULS",
    "STAFFA",
    "STAPLES",
    "STAYNER",
    "STE ANNE DE PRESCOTT",
    "STELLA",
    "STEVENSVILLE",
    "STIRLING",
    "STITTSVILLE",
    "STOKES BAY",
    "STONECLIFFE",
    "STONEY CREEK",
    "STOUFFVILLE",
    "STRAFFORDVILLE",
    "STRATFORD",
    "STRATHROY",
    "STRATTON",
    "STURGEON FALLS",
    "SUDBURY",
    "SUMMERSTOWN",
    "SUNDERLAND",
    "SUNDRIDGE",
    "SUTTON WEST",
    "SWASTIKA",
    "SYDENHAM",
    "TAMWORTH",
    "TARA",
    "TARZWELL",
    "TAVISTOCK",
    "TECUMSEH",
    "TEESWATER",
    "TEETERVILLE",
    "TEHKUMMAH",
    "TEMAGAMI",
    "TERRA COTTA",
    "TERRACE BAY",
    "THAMESFORD",
    "THAMESVILLE",
    "THE ARCHIPELAGO",
    "THEDFORD",
    "THESSALON",
    "THOMASBURG",
    "THORNBURY",
    "THORNDALE",
    "THORNE",
    "THORNHILL",
    "THORNLOE",
    "THORNTON",
    "THOROLD",
    "THUNDER BAY",
    "TICHBORNE",
    "TILBURY",
    "TILDEN LAKE",
    "TILLSONBURG",
    "TIMMINS",
    "TINY",
    "TIVERTON",
    "TOBERMORY",
    "TOLEDO",
    "TORONTO",
    "TORRANCE",
    "TORY HILL",
    "TOTTENHAM",
    "TOWN OF PLYMPTON WYOMING",
    "TOWNSEND",
    "TOWNSHIP OF WILMOT",
    "TRENT LAKES",
    "TRENT RIVER",
    "TRENTON",
    "TROUT CREEK",
    "TROY",
    "TUPPERVILLE",
    "TURKEY POINT",
    "TWEED",
    "UNION",
    "UNIONVILLE",
    "UTOPIA",
    "UTTERSON",
    "UXBRIDGE",
    "VAL CARON",
    "VAL GAGNE",
    "VAL RITA",
    "VAL THERESE",
    "VANESSA",
    "VANIER",
    "VANKLEEK HILL",
    "VARNA",
    "VARS",
    "VAUGHAN",
    "VERMILION BAY",
    "VERNER",
    "VERNON",
    "VERONA",
    "VICTORIA HARBOUR",
    "VIENNA",
    "VINELAND",
    "VINELAND STATION",
    "VIRGIL",
    "VIRGINIATOWN",
    "VITTORIA",
    "WABIGOON",
    "WAHNAPITAE",
    "WAINFLEET",
    "WALKERTON",
    "WALLACEBURG",
    "WALLACETOWN",
    "WALLENSTEIN",
    "WALSINGHAM",
    "WALTERS FALLS",
    "WALTON",
    "WARDSVILLE",
    "WARE",
    "WARKWORTH",
    "WARMINSTER",
    "WARREN",
    "WARSAW",
    "WARWICK TOWNSHIP",
    "WASAGA BEACH",
    "WASHAGO",
    "WATERDOWN",
    "WATERFORD",
    "WATERLOO",
    "WATFORD",
    "WAUBAUSHENE",
    "WAWA",
    "WEBBWOOD",
    "WELLAND",
    "WELLANDPORT",
    "WELLESLEY",
    "WELLINGTON",
    "WENDOVER",
    "WEST GUILFORD",
    "WEST LORNE",
    "WEST MONTROSE",
    "WESTBROOK",
    "WESTMEATH",
    "WESTPORT",
    "WESTWOOD",
    "WHEATLEY",
    "WHITBY",
    "WHITE LAKE",
    "WHITE RIVER",
    "WHITEFISH",
    "WHITEFISH FALLS",
    "WHITNEY",
    "WIARTON",
    "WIKWEMIKONG",
    "WILBERFORCE",
    "WILKESPORT",
    "WILLIAMSBURG",
    "WILLIAMSFORD",
    "WILLIAMSTOWN",
    "WILLISVILLE",
    "WILLOW BEACH",
    "WILNO",
    "WILSONVILLE",
    "WINCHESTER",
    "WINCHESTER SPRINGS",
    "WINDERMERE",
    "WINDHAM CENTRE",
    "WINDSOR",
    "WINGHAM",
    "WOLFE ISLAND",
    "WOODBRIDGE",
    "WOODHAM",
    "WOODLAWN",
    "WOODSTOCK",
    "WOODVILLE",
    "WOOLER",
    "WORTHINGTON",
    "WROXETER",
    "WYEBRIDGE",
    "WYOMING",
    "YARKER",
    "YORK",
    "YORK.",
    "ZEPHYR",
    "ZHIIBAAHAASING",
    "ZURICH",

    # Additional cities/municipalities from validation
    "HALTON HILLS",
    "KAWARTHA LAKES",
    "WHITCHURCH-STOUFFVILLE",
    "CHATHAM-KENT",
    "NIAGARA-ON-THE-LAKE",
    "CLARINGTON",
    "BRADFORD WEST GWILLIMBURY",
    "CLARENCE-ROCKLAND",
    "PRINCE EDWARD",
    "WINNIPEG",  # Manitoba - included for border properties
    "GREATER SUDBURY",
    "ST. CATHARINES",
    "ST. THOMAS",
    "SAULT STE MARIE",
    "SAINT CATHARINES",
}


# Amalgamated cities mapping
# Maps old municipality names to current amalgamated city
AMALGAMATED_CITIES = {
    # Toronto amalgamation (1998)
    "SCARBOROUGH": "TORONTO",
    "ETOBICOKE": "TORONTO",
    "NORTH YORK": "TORONTO",
    "YORK": "TORONTO",
    "EAST YORK": "TORONTO",

    # Hamilton amalgamation (2001)
    "ANCASTER": "HAMILTON",
    "DUNDAS": "HAMILTON",
    "FLAMBOROUGH": "HAMILTON",
    "STONEY CREEK": "HAMILTON",
    "GLANBROOK": "HAMILTON",

    # Ottawa amalgamation (2001)
    "NEPEAN": "OTTAWA",
    "KANATA": "OTTAWA",
    "GLOUCESTER": "OTTAWA",
    "VANIER": "OTTAWA",
    "CUMBERLAND": "OTTAWA",
    "OSGOODE": "OTTAWA",
    "RIDEAU": "OTTAWA",
    "WEST CARLETON": "OTTAWA",
    "GOULBOURN": "OTTAWA",

    # Common variations/aliases
    "GEORGTOWN": "GEORGETOWN",  # Typo
    "STOUFVILLE": "STOUFFVILLE",  # Typo
    "N. YORK": "NORTH YORK",  # Abbreviation
    "E. YORK": "EAST YORK",  # Abbreviation
    "N. BAY": "NORTH BAY",  # Abbreviation
    "ST. CATHARINES": "ST CATHARINES",  # Punctuation variation
    "ST. THOMAS": "ST THOMAS",  # Punctuation variation
    "SAULT STE MARIE": "SAULT STE. MARIE",  # Punctuation variation
    "GREATER SUDBURY": "SUDBURY",  # Name variation
    "GRAND SUDBURY (SUDBURY)": "SUDBURY",  # Old name
    "WINNIPEG": "WINNIPEG",  # Manitoba city (border cases)
    "SAINT CATHARINES": "ST CATHARINES",  # Spelling variation
    "ORLEANS": "ORLÉANS",  # Accent variation
}


# Sub-municipality patterns that should be removed
SUB_MUNICIPALITY_SUFFIXES = [
    "(SCARBOROUGH)",
    "(ETOBICOKE)",
    "(NORTH YORK)",
    "(YORK)",
    "(EAST YORK)",
    "(ANCASTER)",
    "(DUNDAS)",
    "(FLAMBOROUGH)",
    "(STONEY CREEK)",
    "(GLANBROOK)",
    "(GEORGETOWN)",
    "(ALCONA)",
    "(COOKSTOWN)",
    "(ALLISTON)",
    "(OLD TORONTO)",
    "(NEPEAN)",
    "(GLOUCESTER)",
    "(KANATA)",
]


def normalize_city(city: str | None) -> str | None:
    """
    Normalize a city name to its canonical form.

    - Uppercases
    - Removes sub-municipality suffixes like "(Scarborough)"
    - Maps amalgamated cities to current name
    - Returns None if city is None or empty

    Args:
        city: Raw city string from source data

    Returns:
        Normalized city name, or None if invalid
    """
    if not city:
        return None

    # Uppercase
    city_upper = city.strip().upper()

    # Remove sub-municipality suffixes
    for suffix in SUB_MUNICIPALITY_SUFFIXES:
        if suffix in city_upper:
            city_upper = city_upper.replace(suffix, "").strip()

    # Map amalgamated cities
    city_upper = AMALGAMATED_CITIES.get(city_upper, city_upper)

    return city_upper if city_upper else None


def is_valid_city(city: str | None) -> bool:
    """
    Check if a city name is in the valid Ontario cities list.

    Args:
        city: City name to validate (will be normalized first)

    Returns:
        True if city is valid, False otherwise
    """
    if not city:
        return False

    normalized = normalize_city(city)
    return normalized in VALID_ONTARIO_CITIES


def is_likely_unit_or_address(city: str | None) -> bool:
    """
    Check if a "city" value actually contains unit numbers or address components.

    Args:
        city: Value from city field

    Returns:
        True if this looks like a unit/suite/address, not a city
    """
    if not city:
        return False

    city_upper = city.strip().upper()

    # Check for unit/suite indicators
    unit_patterns = [
        r'\bUNIT\b',
        r'\bSUITE\b',
        r'\bAPT\b',
        r'\bAPARTMENT\b',
        r'#\d+',  # Matches #42, #123, etc.
        r'\bUNIT\s*#',
        r'\bSUITE\s*#',
    ]

    import re
    for pattern in unit_patterns:
        if re.search(pattern, city_upper):
            return True

    # Check for street address indicators
    address_patterns = [
        r'\bSTREET\b',
        r'\bROAD\b',
        r'\bAVENUE\b',
        r'\bBOULEVARD\b',
        r'\bBLVD\b',
        r'\bDRIVE\b',
        r'\bLANE\b',
        r'\bCOURT\b',
        r'\bCRESCENT\b',
        r'\bCRES\b',
        r'\bPLACE\b',
        r'\bTRAIL\b',
        r'\bWAY\b',
        r'\bCIRCLE\b',
        r'\bPKWY\b',
        r'\bPARKWAY\b',
        r'\bHWY\b',
        r'\bHIGHWAY\b',
    ]

    for pattern in address_patterns:
        if re.search(pattern, city_upper):
            return True

    # Check if starts with a number (likely street number)
    if re.match(r'^\d+', city_upper):
        return True

    return False


def extract_city_from_canonical(canonical: str | None) -> str | None:
    """
    Extract city from a canonical address string.

    Expected format: "STREET ADDRESS, CITY, PROVINCE, COUNTRY"
    Example: "9025 AIRPORT ROAD, UNIT 1, BRAMPTON, CA"

    Args:
        canonical: Canonical address string

    Returns:
        Extracted city name, or None if not found
    """
    if not canonical:
        return None

    # Split by comma
    parts = [p.strip() for p in canonical.split(',')]

    if len(parts) < 3:
        return None

    # Check if second-to-last part is a province (ON, ONTARIO)
    potential_province = parts[-2].upper()
    if potential_province in ('ON', 'ONTARIO'):
        # City is the part before province
        city_idx = -3
        if len(parts) > abs(city_idx):
            city = parts[city_idx].strip()
            # Validate it's actually a city
            if is_valid_city(city):
                return normalize_city(city)

    # Try second-to-last part as city (for "STREET, CITY, COUNTRY" format)
    if len(parts) >= 3:
        city = parts[-2].strip()
        if is_valid_city(city):
            return normalize_city(city)

    # Look for any valid city in the parts
    for part in parts[1:]:  # Skip first part (street address)
        part_clean = part.strip()
        if is_valid_city(part_clean):
            return normalize_city(part_clean)

    return None
